CREATE TABLE `product` (
  `product_code` varchar(255) DEFAULT NULL,
  `O_price` int DEFAULT NULL,
  `R_price` int DEFAULT NULL,
  `category_1` varchar(255) DEFAULT NULL,
  `category_2` varchar(255) DEFAULT NULL,
  `category_3` varchar(255) DEFAULT NULL,
  `favorite_N` int DEFAULT '0',
  `genre_code` varchar(255) DEFAULT NULL,
  `is_deleted` int DEFAULT '0',
  `judge` varchar(255) DEFAULT NULL,
  `payment_N` int DEFAULT '0',
  `product_R_date` datetime(6) DEFAULT NULL,
  `product_img_0` varchar(255) DEFAULT NULL,
  `product_img_1` varchar(255) DEFAULT NULL,
  `product_img_2` varchar(255) DEFAULT NULL,
  `product_img_3` varchar(255) DEFAULT NULL,
  `product_img_4` varchar(255) DEFAULT NULL,
  `product_img_5` varchar(255) DEFAULT NULL,
  `product_name` varchar(255) DEFAULT NULL,
  `review_N` int DEFAULT '0',
  `product_brand` varchar(255) DEFAULT NULL,
  `product_num` int NOT NULL AUTO_INCREMENT,
  `product_registrant` varchar(255) DEFAULT NULL,
  `product_gender` int DEFAULT NULL,
  PRIMARY KEY (`product_num`)
) ENGINE=InnoDB AUTO_INCREMENT=6391 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;